CREATE TABLE goals (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '目标ID',
    title VARCHAR(255) NOT NULL COMMENT '目标标题',
    description TEXT COMMENT '目标描述',
    status VARCHAR(50) NOT NULL DEFAULT 'draft' COMMENT '目标状态',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='目标表';
